export const texto = {
  intro: "Bienvenidos a mi portafolio, el mismo esta creado para mobile first y tiene intenciones de ser responsive y poder utilizarse y modificarse desde la misma pagina.",
  intro2: "Navegue utilizando las flechas y presionando enter o space para un mayor efecto arcade",
  back: "Volver",
  title_options:"Opciones",
  language:"Idioma",
  mode:"Modo Oscuro",
  start:"Empezar Partida",
  continue: "Continuar Partida",
  load: "Cargar Partida",
  level: "Nivel",
  name: "Nombre",
  clans: "Clanes",
  class: "Clase",
  about: "Acerca de",
  skills: "Habilidades",
  projects: "Proyectos",
}