export const textEng = {
    intro: "Welcome to my portafolio. The same one it was created with react, atomos,firebase and love.",
    intro2: "Navigate using the keyboard arrows to improve the experience like video games.",
    back: "Back",
    title_options:"Options",
    language:"Language",
    mode:"Dark Mode",
    start:"Start Game",
    continue: "Continue Game",
    load: "Load Game",
    level: "Level",
    name: "Name",
    clans: "Clans",
    class: "Class",
    about: "About Me",
    skills: "Skills",
    projects: "Projects",
    tech: "Technologies",
    social: "Social",
    portafolio:"Nico's Profile",
  }